version: 2

project_name: chita

before:
  hooks:
    - go mod tidy

builds:
  - id: chita
    main: .
    binary: chita
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/chitacloud/chita-cli/cmd.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

brews:
  - name: chita
    repository:
      owner: chitacloud
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://app.chitacloud.com"
    description: "Chita Cloud CLI"
    license: "MIT"
    install: |
      bin.install "chita"
    test: |
      system "#{bin}/chita", "--version"

release:
  github:
    owner: chitacloud
    name: chita-cli
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
